// <auto-generated />
using System;
using LIPAJOLI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIPAJOLI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827183037_initale")]
    partial class initale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("LIPAJOLI.Models.Emprunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLimiteRetour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExemplaireId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivreId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsagerNoAbonne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExemplaireId");

                    b.HasIndex("LivreId");

                    b.HasIndex("UsagerNoAbonne");

                    b.ToTable("Emprunts", (string)null);
                });

            modelBuilder.Entity("LIPAJOLI.Models.Exemplaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeLivre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LivreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LivreId");

                    b.ToTable("Exemplaires", (string)null);
                });

            modelBuilder.Entity("LIPAJOLI.Models.Livre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auteurs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN10")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN13")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Livres", (string)null);
                });

            modelBuilder.Entity("LIPAJOLI.Models.Usager", b =>
                {
                    b.Property<string>("NoAbonne")
                        .HasColumnType("TEXT");

                    b.Property<int>("Defaillance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoAbonne");

                    b.ToTable("Usagers", (string)null);
                });

            modelBuilder.Entity("LIPAJOLI.Models.Emprunt", b =>
                {
                    b.HasOne("LIPAJOLI.Models.Exemplaire", null)
                        .WithMany("Emprunts")
                        .HasForeignKey("ExemplaireId");

                    b.HasOne("LIPAJOLI.Models.Livre", "Livre")
                        .WithMany("Emprunts")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIPAJOLI.Models.Usager", "Usager")
                        .WithMany("Emprunts")
                        .HasForeignKey("UsagerNoAbonne")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Usager");
                });

            modelBuilder.Entity("LIPAJOLI.Models.Exemplaire", b =>
                {
                    b.HasOne("LIPAJOLI.Models.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("LivreId");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("LIPAJOLI.Models.Exemplaire", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("LIPAJOLI.Models.Livre", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("LIPAJOLI.Models.Usager", b =>
                {
                    b.Navigation("Emprunts");
                });
#pragma warning restore 612, 618
        }
    }
}
